Featue/add azuredevops synchronizer
quantori/GherkinSyncTool pull request #9
Opened 2021-10-27 14:54 UTC by Brrovko

2021-10-30 04:42 UTC, Brrovko commented on GherkinSyncTool.Synchronizers.AzureDevOps/AzureDevopsSynchronizer.cs
> +            var fullPath = baseDirectory.Parent.FullName + Path.DirectorySeparatorChar + relativePath;
Could you please give an example?

2021-10-30 04:44 UTC, Brrovko commented on GherkinSyncTool.Synchronizers.AzureDevOps/Client/AzureDevopsClient.cs
> +            const int batchRequestLimit = 200;
It is a constant value for Azure DevOps API. This is not a variable.

2021-10-30 04:47 UTC, Brrovko commented on GherkinSyncTool.Synchronizers.AzureDevOps/Content/CaseContentBuilder.cs
> +            var steps = GetSteps(scenario, featureFile);
Not now. But it is definitely needed for the next task about content seeding.

2021-11-01 06:46 UTC, vladimir-s-quantory commented on GherkinSyncTool.Synchronizers.AzureDevOps/Client/AzureDevopsClient.cs
> +            const int batchRequestLimit = 200;
Then I guess it will be a good thing to add comment above about that

2021-11-01 14:13 UTC, Brrovko commented on GherkinSyncTool.Synchronizers.TestRail/Content/CaseContentBuilder.cs
> +        private readonly TestRailSettings _testRailSettings = ConfigurationManager.GetConfiguration<TestRailConfigs>().TestRailSettings;
We have ValidateConfigs() method for all IConfigs inheritors and the null reference exception validates there.

2021-11-02 06:17 UTC, Brrovko commented on GherkinSyncTool.Synchronizers.AzureDevOps/Client/AzureDevopsClient.cs
> +            const int batchRequestLimit = 200;
Done

2021-11-02 06:17 UTC, Brrovko commented on GherkinSyncTool.Synchronizers.AzureDevOps/Content/CaseContentBuilder.cs
> +                    Path = "/fields/" + WorkItemFields.Description,
Done

2021-11-02 06:17 UTC, Brrovko commented on GherkinSyncTool.Synchronizers.AzureDevOps/Content/CaseContentBuilder.cs
> +                    Path = "/" + WorkItemFields.Id,
Done

2021-11-02 06:17 UTC, Brrovko commented on GherkinSyncTool.Synchronizers.AzureDevOps/Content/CaseContentBuilder.cs
> +                    Path = "/fields/" + WorkItemFields.Title,
Done

2021-11-02 06:18 UTC, Brrovko commented on GherkinSyncTool.Synchronizers.AzureDevOps/Content/CaseContentBuilder.cs
> +                var fullStep = $"**{step.Keyword.Trim()}** " + step.Text.Replace("<","***").Replace(">","***");
Fixed

2021-11-02 06:18 UTC, Brrovko commented on GherkinSyncTool.Synchronizers.TestRail/TestRailSynchronizerModule.cs
> +        //TODO:
Done

2021-11-02 07:00 UTC, ILastovka requested changes

2021-11-02 07:29 UTC, Brrovko commented on GherkinSyncTool.Synchronizers.TestRail/Model/TestRailConfigs.cs
> +            if (string.IsNullOrWhiteSpace(TestRailSettings.BaseUrl) ||
The empty is covered as well.
![image](https://user-images.githubusercontent.com/24970976/139803657-c362628c-7d77-48fc-9368-d3664f84f040.png)

2021-11-02 07:39 UTC, ILastovka approved these changes

2021-11-02 07:56 UTC, vladimir-s-quantory commented on GherkinSyncTool.Synchronizers.AzureDevOps/AzureDevopsSynchronizer.cs
> +            var fullPath = baseDirectory.Parent.FullName + Path.DirectorySeparatorChar + relativePath;
`Path.Combine(baseDirectory.Parent.FullName, relativePath);`
When working with Linux it is even better to use DirectoryInfo, but it needs some testing and refactoring. Let's keep the things this way for now I guess

2021-11-02 08:11 UTC, vladimir-s-quantory approved these changes

2021-11-02 08:17 UTC, vladimir-s-quantory approved these changes

2021-11-02 08:18 UTC, merged